version: '3'
services:
  mongodb-server:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-server

volumes:
  data: